[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add the zk verifier contracts from Noir
remappings = [
    "verifier/=circuits/contract/",
]
fs_permissions = [{ access = "read", path = "./circuits/proofs/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
